### ISSUE TITLE
--split-per-abi support

### ISSUE THREAD

**Issue by kwent** [dotdoom/fastlane-plugin-flutter#11]
Hi,

Is --split-per-abi  supported ? 

Also i see some references to `appbundle` in code but i'm not sure how to use it ? need more documentation probably.

Thanks a lot !

Regards

**Comment by dotdoom** [comment]
Hi! I do use `appbundle` and it works well. It can be used like that:

```ruby
flutter_build(build: "appbundle")
```

Is this what you're looking for, or would you like to have some other topic covered by documentation?

If you haven't had a chance yet, make sure to check out [example Fastfile](https://github.com/dotdoom/fastlane-plugin-flutter/blob/master/fastlane/Fastfile) as well.

I didn't use `split-per-abi`, will check it out. This will need some code to be supported. Thanks for the idea!
