### ISSUE TITLE
Seems to supply not work in flutter project root

### ISSUE THREAD

**Issue by dfdgsdfg** [dotdoom/fastlane-plugin-flutter#12]
I try to supply play store internal test, but it returns `[!] No authentication parameters were specified. These must be provided in order to authenticate with Google`

Work in android folder with another fastlane env, it works fine.

Any workaround?

https://github.com/fastlane/fastlane/issues/15457

**Comment by dfdgsdfg** [comment]
Oh.. I missed `fastlane/Appfile`'s json_key_file property.

Thanks. 😄

**Comment by dotdoom** [comment]
Cool! Glad it worked... I'll add some documentation on how I layout fastlane in our projects.

**Comment by dfdgsdfg** [comment]
Check this out

http://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials

```
## fastlane/Appfile

json_key_file("android/api-111-222-333.json")
```

**Comment by raveesh-me** [comment]
My json_key_file is set properly, supply could initialize once as well.
But again I am getting this error
