### ISSUE TITLE
Building ipa for flutter 2.0.X

### ISSUE THREAD

**Issue by ltropin** [dotdoom/fastlane-plugin-flutter#19]
Add feature build ipa for flutter 2.0.X

**Comment by dfdgsdfg** [comment]
https://github.com/dotdoom/fastlane-plugin-flutter/issues/18

**Comment by dotdoom** [comment]
One problem with building IPA is that "flutter build ipa" does not really produce a distribution-ready IPA and instead creates an xcarchive which can be used to create one (with the help of Xcode).

I can probably try to work around that by employing fastlane's own magic, but it may take a while.

**Comment by ltropin** [comment]
Don't worry i solve the problem.

> #18

Thanks.

**FastLane file:**
<pre>
exportfile_path = "ios/Runner/OptionsPlist.plist"
flutter_build(
  build: 'ipa',
  build_args: [
    "--export-options-plist=./#{exportfile_path}"
  ]
)</pre>



**OptionsPlist.plist file:**
<pre>
&lt;plist version="1.0"&gt;
     &lt;dict&gt;
        &lt;key>uploadSymbols&lt;/key&gt;
         &lt;false/&gt;
         &lt;key>uploadBitcode&lt;/key&gt;
         &lt;false/&gt;
         &lt;key&gt;method&lt;/key&gt;
         &lt;string&gt;ad-hoc&lt;/string&gt;
         &lt;key&gt;compileBitcode&lt;/key&gt;
         &lt;false/&gt;
     &lt;/dict&gt;
&lt;/plist&gt;

</pre>
