### ISSUE TITLE
"No such file or directory" for ".../android/vendor/flutter/bin/flutter"

### ISSUE THREAD

**Issue by tys-martin-haintz** [dotdoom/fastlane-plugin-flutter#24]
Hi,

I am getting this error message. seems like flutter is not installed. what did I miss in my setup?

`[15:43:57]: No such file or directory - /home/runner/work/app_tracker/app_tracker/android/vendor/flutter/bin/flutter`

Thanks

**Comment by tys-martin-haintz** [comment]
ah, I missed to call the bootsrap lane.

**Comment by dotdoom** [comment]
Right, bootstrap lane will install flutter into this "vendor" directory. If you rather reuse existing system-wide installation, please add flutter tool to `PATH` or set `FLUTTER_HOME` environment variable!
