### ISSUE TITLE
Use of flutter_flavorizr in flutter_build

### ISSUE THREAD

**Issue by felicesim** [dotdoom/fastlane-plugin-flutter#32]
Hello,
I'm trying to use [flutter_flavorizr](https://pub.dev/packages/flutter_flavorizr) and build apk of the desired flavor.

Flutter command for flavor 'dev' be like: `flutter build apk --flavor dev -t lib/main_dev.dart`

So I tried in my FastFile in these ways: 

1. ` flutter_build(
           build: "apk",
           build_args: ["--flavor dev", "-t lib/main_dev.dart"]
         )`

or 

2. `build_args = []`
       `args = "--flavor dev -t lib/main_dev.dart"`
       `build_args << args`

`flutter_build(
           build: "apk",
           build_args: build_args
         )`

But I received the error

flutter build apk --flavor\\ dev -t\\ lib/main_dev.dart
[pid 90368 exit 1]

Target file " lib/main_dev.dart" not found.

I also tried absolute path for the main_dev.dart file.

------------------------------------

Someone could help me?

**Comment by dotdoom** [comment]
The problem is that each item in `build_args` is treated as a single flag.

So, it should work if you put it like that:

```ruby
build_args += ["--flavor", "dev", "-t", "lib/main_dev.dart"]
```

or

```ruby
build_args << "--flavor"
build_args << "dev"
build_args << "-t"
build_args << "lib/main_dev.dart"
```

or even

```ruby
build_args += %w(--flavor dev -t lib/main_dev.dart)
```
which are all equivalent in Ruby.
