### ISSUE TITLE
flutter_build can't parse built file path after upstream Flutter change

### ISSUE THREAD

**Issue by WillSoper** [dotdoom/fastlane-plugin-flutter#37]
The Flutter team have changed the [Flutter build output in this commit](https://github.com/flutter/flutter/commit/9ae8a6b7d54efd1efa6ceff935ceab02701b4c8e), removing the period from the end of the line.

That change causes [this Regex in flutter_build_action.rb](https://github.com/dotdoom/fastlane-plugin-flutter/blob/0759c476132409cc1dce6a2337c5a7579e3acb5d/lib/fastlane/plugin/flutter/actions/flutter_build_action.rb#L120) to no longer match, and the built file path is no longer returned (we see the error **Cannot parse built file path from "flutter build"**)

If you could update that regex from `/Built (.*?)(:? \([^)]*\))?\.$/` to be `/Built (.*?)(:? \([^)]*\))?\.?$/` (making the trailing period optional), that should fix it for both the old and new format, I think!

**Comment by dotdoom** [comment]
The fix is now live in v0.8.0
