### ISSUE TITLE
Why this plugin doesn't show on the _available-plugins_ in Fastlane's site?

### ISSUE THREAD

**Issue by fxsalazar** [dotdoom/fastlane-plugin-flutter#5]

**Comment by dotdoom** [comment]
Thanks for letting us know; https://github.com/fastlane/fastlane/issues/15897 reported upstream.

**Comment by dotdoom** [comment]
The plugin is now back in the list, upstream issue still open for follow-up.

https://docs.fastlane.tools/plugins/available-plugins/
